In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [61]:
df=pd.read_csv("/content/Dataset .csv")

In [62]:
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [63]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [32]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [44]:
df['Aggregate rating']

0       4.8
1       4.5
2       4.4
3       4.9
4       4.8
       ...
9546    4.1
9547    4.2
9548    3.7
9549    4.0
9550    4.0
Name: Aggregate rating, Length: 9551, dtype: float64

In [65]:
# Another correct way using the columns keyword argument explicitly
df = df.drop(columns=[ 'Country Code', 'City','Longitude', 'Locality','Latitude', 'Currency', 'Has Table booking',
                     'Has Online delivery', 'Locality Verbose','Is delivering now','Rating color','Address'], axis=1)

In [66]:
df = pd.get_dummies(df, drop_first=True)

In [70]:
df

,Restaurant ID,Average Cost for two,Price range,Aggregate rating,Votes,Restaurant Name_#Dilliwaala6,Restaurant Name_#InstaFreeze,Restaurant Name_#OFF Campus,Restaurant Name_#Urban Caf��,Restaurant Name_#hashtag,...,"Cuisines_Western, Asian, Cafe","Cuisines_Western, Fusion, Fast Food",Cuisines_World Cuisine,"Cuisines_World Cuisine, Mexican, Italian","Cuisines_World Cuisine, Patisserie, Cafe",Rating text_Excellent,Rating text_Good,Rating text_Not rated,Rating text_Poor,Rating text_Very Good
0,6317637,1100,3,4.8,314,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,6304287,1200,3,4.5,591,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,6300002,4000,4,4.4,270,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,6318506,1500,4,4.9,365,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,6314302,1500,4,4.8,229,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,80,3,4.1,788,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
9547,5908749,105,3,4.2,1034,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
9548,5915807,170,4,3.7,661,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
9549,5916112,120,4,4.0,901,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
9550,5927402,55,2,4.0,591,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [71]:
df.columns

Index(['Restaurant ID', 'Average Cost for two', 'Price range',
       'Aggregate rating', 'Votes', 'Restaurant Name_#Dilliwaala6',
       'Restaurant Name_#InstaFreeze', 'Restaurant Name_#OFF Campus',
       'Restaurant Name_#Urban Caf��', 'Restaurant Name_#hashtag',
       ...
       'Cuisines_Western, Asian, Cafe', 'Cuisines_Western, Fusion, Fast Food',
       'Cuisines_World Cuisine', 'Cuisines_World Cuisine, Mexican, Italian',
       'Cuisines_World Cuisine, Patisserie, Cafe', 'Rating text_Excellent',
       'Rating text_Good', 'Rating text_Not rated', 'Rating text_Poor',
       'Rating text_Very Good'],
      dtype='object', length=9279)

In [72]:
X = df.drop('Aggregate rating', axis=1)
y = df['Aggregate rating']

In [73]:
X.shape

(9551, 9278)

In [74]:
y.shape

(9551,)

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [77]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [78]:
y_pred = model.predict(X_test)

In [79]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [80]:
mse

6.1650653137748055

In [81]:
# For linear regression, coefficients can be used to understand feature importance
if isinstance(model, LinearRegression):
    feature_importance = pd.DataFrame({
        'Feature': X_train.columns,
        'Importance': model.coef_
    }).sort_values(by='Importance', ascending=False)

    print(feature_importance)

                                             Feature  Importance
5901                            Restaurant Name_Skye   85.893223
43                    Restaurant Name_3 Wise Monkeys   53.631336
6174                      Restaurant Name_Sushi Masa   43.232844
508      Restaurant Name_Avec Moi Restaurant and Bar   22.537939
8371                        Cuisines_French, Western   22.537939
...                                              ...         ...
6697  Restaurant Name_The Library - The Leela Palace  -16.971018
2941         Restaurant Name_Hobnob Gourmet Caf��bar  -17.167365
6134               Restaurant Name_Summer House Cafe  -17.188692
1057           Restaurant Name_By The Way - Bellagio  -17.509357
3444                      Restaurant Name_Kawa Sushi  -21.892456

[9278 rows x 2 columns]

In [82]:
baseline_mse = mean_squared_error(y_test, [y_train.mean()] * len(y_test))
print(f'Baseline MSE: {baseline_mse}')

Baseline MSE: 2.2771267376323148

In [83]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2}')

R-squared: -1.7085984634402496